name: sectar
dependencies:
- certifi=2016.2.28=py35_0
- cffi=1.10.0=py35_0
- freetype=2.5.5=2
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- libpng=1.6.30=1
- libtiff=4.0.6=3
- mako=1.0.6=py35_0
- markupsafe=1.0=py35_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py35_3
- nose=1.3.7=py35_1
- olefile=0.44=py35_0
- openssl=1.0.2l=0
- pillow=4.2.1=py35_0
- pip=9.0.1=py35_1
- pycparser=2.18=py35_0
- pygpu=0.6.9=py35_0
- python=3.5.4=0
- readline=6.2=2
- scipy=0.19.1=np113py35_0
- setuptools=36.4.0=py35_0
- six=1.10.0=py35_0
- cuda80=1.0
- pytorch=0.2.0
- torchvision=0.1.9
- sqlite=3.13.0=0
- theano=0.9.0=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - awscli==1.11.168
  - backports.weakref==1.0rc1
  - bleach==1.5.0
  - boto==2.48.0
  - boto3==1.4.7
  - botocore==1.7.26
  - cached-property==1.3.1
  - chardet==3.0.4
  - click==6.7
  - cloudpickle==0.4.0
  - colorama==0.3.7
  - cycler==0.10.0
  - decorator==4.1.2
  - docutils==0.14
  - flask==0.12.2
  - gym==0.9.3
  - html5lib==0.9999999
  - idna==2.6
  - ipython-genutils==0.2.0
  - itsdangerous==0.24
  - jinja2==2.9.6
  - jmespath==0.9.3
  - joblib==0.11
  - jsonschema==2.6.0
  - jupyter-core==4.3.0
  - markdown==2.6.9
  - matplotlib==2.0.2
  - mujoco-py==0.5.7
  - nbformat==4.4.0
  - numpy==1.14.4
  - packaging==16.8
  - path.py==10.4
  - pathlib==1.0.1
  - plotly==2.0.15
  - protobuf==3.4.0
  - psutil==5.1.3
  - pyasn1==0.3.7
  - pyglet==1.2.4
  - pyopengl==3.1.0
  - pyparsing==2.2.0
  - pyprind==2.11.1
  - python-dateutil==2.6.1
  - python-gnupg==0.4.1
  - pytz==2017.2
  - pyyaml==3.12
  - requests==2.18.4
  - rsa==3.4.2
  - s3transfer==0.1.11
  - scikit-learn==0.19.0
  - sklearn==0.0
  - tensorflow-gpu==1.3.0
  - tensorflow-tensorboard==0.1.6
  - traitlets==4.3.2
  - urllib3==1.22
  - werkzeug==0.12.2

